name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: dockerci:1.0.0
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Dockerfile
      - run: docker build -t $IMAGE_NAME ./
      - run: docker container run --rm $IMAGE_NAME --volume="$(pwd)":"$(pwd)" --workdir="$(pwd)" npm run lint